"""
Django settings for bilhyd project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lj#_qho%ee+m^b%3k(rm&m4fb=#78ty*7_o-9y4@eyv)d!m&zp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] #tout adresse ip peut heberger notre application

# Application definition

INSTALLED_APPS = [
    # whitenoise

    # My application
    'app',
    'bilhyd',  # ito natao ato satria ampiasa modele aho, raha tsy mampiasa modele dia afaka tsy atao ato
    'whitenoise.runserver_nostatic', # ilaina miaraka am whitenoise (rehefa tsy mety mahita static files)
    # Django application
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware', # ilaina miaraka am whitenoise (rehefa tsy mety mahita static files)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bilhyd.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bilhyd.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
    # ilay .com tsy ao anaty boky fa nandramako mihitsy (miasa ao am template welcome io)
    # ilaina amin'ny attribut "href" ny STATIC_URL ... izany hoe: ao am lien /static.com/ no misy ny dossier static...
    # ...izay no-parametrer-na ao amin'ny STATICFILES_DIRS
STATIC_URL = 'static.com/'  # Les fichiers statiques (CSS et JVscript seront accessible via l'url 'static.com' (Boky page 213)

STATIC_ROOT = os.path.join(BASE_DIR, 'static/STATICROOT')

STATICFILES_DIRS = [     # ces fichies statiques seront placés dans le dossier src/static (Boky page 213)
        os.path.join(BASE_DIR, 'static'), # cette repertoire est donc trouvé dans l'url static.com
    ]


APPEND_SLASH = True
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# IRETO PARAMETRE MEDIA IRETO DIA AMBOARINA FA TSY MISY PAR DEFAUT... rehefa vita ireto dia amboarina ihany koa
# any amin'ny urls.py ka toa izao no atao any :
            # (from django.conf import settings, from django.conf.urls.static import static)
            # urlpatterns=[ les paths ...
                            # ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
MEDIA_URL = '/media.com/'  # manondro ao am path BASE_DIR(io ambany ao am MEDIA_ROOT io) ny url "media.com" (ilaina am download)
MEDIA_ROOT = BASE_DIR   # Emplacement des fichiers televersé par l'utilisateur (Django website : Managing files)
                        # raha nampiasa upload to (model) dia lasa any ireo fichier
                        # ampiasaina amin'ny 'href' ihany koa ny MEDIA_URL ka io no hahafahana manao download

    # raha tsy misy an'ireo dia tsy afaka manao download izay fichier apetraka ao anaty media mihitsy ny utilisateur

