# Generated by Django 4.1.3 on 2022-12-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('adress', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prénom', models.CharField(max_length=30)),
                ('date_de_naissance', models.DateField(max_length=8)),
                ('téléphone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32, null=True)),
                ('RU', models.FloatField(null=True)),
                ('RFU', models.FloatField(null=True)),
                ('fichier', models.FileField(upload_to='User_data/User_data_upload')),
                ('fichiercalculé', models.FileField(upload_to='')),
                ('friends', models.ManyToManyField(to='bilhyd.person')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bilhyd.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Thorntwaite_coeff_corr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.IntegerField()),
                ('Janvier', models.FloatField()),
                ('Fevrier', models.FloatField()),
                ('Mars', models.FloatField()),
                ('Avril', models.FloatField()),
                ('Mai', models.FloatField()),
                ('Juin', models.FloatField()),
                ('Juillet', models.FloatField()),
                ('Aout', models.FloatField()),
                ('Septembre', models.FloatField()),
                ('Octobre', models.FloatField()),
                ('Novembre', models.FloatField()),
                ('Decembre', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Thorntwaite_etp_non_corrigee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('Etp_non_corrigee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Turc_duree_astro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.IntegerField()),
                ('Janvier', models.FloatField()),
                ('Fevrier', models.FloatField()),
                ('Mars', models.FloatField()),
                ('Avril', models.FloatField()),
                ('Mai', models.FloatField()),
                ('Juin', models.FloatField()),
                ('Juillet', models.FloatField()),
                ('Aout', models.FloatField()),
                ('Septembre', models.FloatField()),
                ('Octobre', models.FloatField()),
                ('Novembre', models.FloatField()),
                ('Decembre', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Turc_radiation_globale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.IntegerField()),
                ('Janvier', models.FloatField()),
                ('Fevrier', models.FloatField()),
                ('Mars', models.FloatField()),
                ('Avril', models.FloatField()),
                ('Mai', models.FloatField()),
                ('Juin', models.FloatField()),
                ('Juillet', models.FloatField()),
                ('Aout', models.FloatField()),
                ('Septembre', models.FloatField()),
                ('Octobre', models.FloatField()),
                ('Novembre', models.FloatField()),
                ('Decembre', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bilhyd.person')),
                ('poste', models.CharField(max_length=15)),
                ('lieu_de_travail', models.CharField(max_length=15)),
            ],
            bases=('bilhyd.person',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('publication_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bilhyd.person')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bilhyd.person')),
                ('année', models.IntegerField()),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bilhyd.cursus')),
            ],
            bases=('bilhyd.person',),
        ),
    ]
